In [5]:
import numpy as np
import matplotlib.pyplot as pp

In [6]:
a = np.array([1,2,3,4,5])

In [7]:
a.dtype#type of the array by 'dtype'


dtype('int32')

In [9]:
a= np.array([1,2,3,4,5],dtype=np.float64)#changing the data type to float64

In [10]:
a

array([1., 2., 3., 4., 5.])

In [14]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.float64)#two dimensional array

In [13]:
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [16]:
b.dtype

dtype('float64')

In [18]:
b.ndim #no. of dimentions


2

In [22]:
b.shape, b.size

(2, 5)

In [23]:
np.zeros((3,3),'d')

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.empty((4,4),'d')

array([[4.67296746e-307, 1.69121096e-306, 8.90070286e-308,
        1.05695846e-307],
       [8.34441742e-308, 1.78022342e-306, 6.23058028e-307,
        9.79107872e-307],
       [6.89807188e-307, 7.56594375e-307, 6.23060065e-307,
        1.78021527e-306],
       [8.34454050e-308, 1.11261027e-306, 1.15706896e-306,
        1.33512173e-306]])

In [25]:
np.linspace(0,10,5)#5 elements btw two extrema's

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [28]:
np.random.standard_normal((2,4))#dim-2rw 4col and random value filling

array([[ 0.04778001,  0.19520168, -1.59959846, -0.79648409],
       [-0.34794173, -1.41653642,  2.13754109, -0.2448093 ]])

In [29]:
a = np.random.standard_normal((2,3))
b = np.random.standard_normal((2,3))
np.vstack([a,b])

array([[ 1.99571196,  1.34599279, -0.28056648],
       [-0.14803952,  0.0753652 ,  0.73983415],
       [-0.75556189, -0.75476011, -0.72481249],
       [-0.9579053 ,  0.45238006,  0.70983739]])

In [30]:
np.hstack([a,b])

array([[ 1.99571196,  1.34599279, -0.28056648, -0.75556189, -0.75476011,
        -0.72481249],
       [-0.14803952,  0.0753652 ,  0.73983415, -0.9579053 ,  0.45238006,
         0.70983739]])

In [31]:
a.transpose()

array([[ 1.99571196, -0.14803952],
       [ 1.34599279,  0.0753652 ],
       [-0.28056648,  0.73983415]])

In [32]:
np.save('example.npy',a)  

In [33]:
al = np.load('example.npy')

In [34]:
al

array([[ 1.99571196,  1.34599279, -0.28056648],
       [-0.14803952,  0.0753652 ,  0.73983415]])